import { ref, computed } from 'vue'
import { defineStore } from 'pinia'

export const useCarStore = defineStore('car', () => {
  const carClasses = ref([
    { id: 1, name: 'Voiture' },
    { id: 2, name: 'SUV' },
    { id: 3, name: 'Camion' },
    { id: 4, name: 'Van' },
  ])

  const carTypes = ref([
    { id: 1, name: 'Citadine' },
    { id: 2, name: 'Berline' },
    { id: 3, name: 'Coupé' },
    { id: 4, name: 'Cabriolet' },
    { id: 5, name: 'Break' },
    { id: 6, name: 'Monospace' },
    { id: 7, name: 'Pick-up' },
    { id: 8, name: '4x4' },
  ])

  const carTransmission = ref([
    { id: 1, name: 'Manuelle' },
    { id: 2, name: 'Automatique' },
  ])

  const carFuelType = ref([
    { id: 1, name: 'Essence' },
    { id: 2, name: 'Diesel' },
    { id: 3, name: 'Électrique' },
    { id: 4, name: 'Hybride' },
  ])

  const carSeats = ref([
    { id: 1, name: '2 sièges' },
    { id: 2, name: '4 sièges' },
    { id: 3, name: '5 sièges' },
    { id: 4, name: '7 sièges' },
  ])

  const carDoors = ref([
    { id: 1, name: '2 portes' },
    { id: 2, name: '4 portes' },
  ])

  const carColors = ref([
    { id: 1, name: 'Rouge' },
    { id: 2, name: 'Bleu' },
    { id: 3, name: 'Noir' },
    { id: 4, name: 'Blanc' },
    { id: 5, name: 'Gris' },
    { id: 6, name: 'Vert' },
    { id: 7, name: 'Jaune' },
    { id: 8, name: 'Orange' },
    { id: 9, name: 'Violet' },
    { id: 10, name: 'Rose' },
  ])

  const carExtras = ref([
    { id: 1, name: 'Climatisation', icon: 'WindIcon' },
    { id: 2, name: 'GPS', icon: 'GpsIcon' },
    { id: 3, name: 'Siège enfant', icon: 'StarIcon' },
    { id: 4, name: 'Toit ouvrant', icon: 'StarIcon' },
    { id: 5, name: 'Bluetooth', icon: 'StarIcon' },
    { id: 6, name: 'Caméra de recul', icon: 'StarIcon' },
    { id: 7, name: 'Système audio premium', icon: 'StarIcon' },
    { id: 8, name: 'Volant chauffant', icon: 'StarIcon' },
    { id: 9, name: 'Sièges chauffants', icon: 'StarIcon' },
    { id: 10, name: 'Régulateur de vitesse', icon: 'StarIcon' },
    { id: 11, name: 'Assistance au stationnement', icon: 'StarIcon' },
    { id: 12, name: 'Détecteur d’angle mort', icon: 'StarIcon' },
    { id: 13, name: 'Aide au maintien de voie', icon: 'StarIcon' },
    { id: 14, name: 'Système de navigation', icon: 'StarIcon' },
    { id: 15, name: 'Chargeur sans fil', icon: 'StarIcon' },
    { id: 16, name: 'Prise USB', icon: 'StarIcon' },
    { id: 17, name: 'Prise 12V', icon: 'StarIcon' },
    { id: 18, name: 'Porte-vélos', icon: 'StarIcon' },
    { id: 19, name: 'Barres de toit', icon: 'StarIcon' },
    { id: 20, name: 'Attelage de remorque', icon: 'StarIcon' },
  ])

  const carBrands = ref([
    { id: 1, name: 'Toyota' },
    { id: 2, name: 'Honda' },
    { id: 3, name: 'Ford' },
    { id: 4, name: 'Chevrolet' },
    { id: 5, name: 'Nissan' },
    { id: 6, name: 'BMW' },
    { id: 7, name: 'Mercedes-Benz' },
    { id: 8, name: 'Volkswagen' },
    { id: 9, name: 'Hyundai' },
    { id: 10, name: 'Kia' },
    { id: 11, name: 'Subaru' },
    { id: 12, name: 'Mazda' },
    { id: 13, name: 'Audi' },
    { id: 14, name: 'Lexus' },
    { id: 15, name: 'Porsche' },
    { id: 16, name: 'Tesla' },
    { id: 17, name: 'Volvo' },
    { id: 18, name: 'Jaguar' },
    { id: 19, name: 'Land Rover' },
    { id: 20, name: 'Mitsubishi' },
    { id: 21, name: 'Fiat' },
    { id: 22, name: 'Chrysler' },
    { id: 23, name: 'Buick' },
    { id: 24, name: 'GMC' },
    { id: 25, name: 'Acura' },
    { id: 26, name: 'Infiniti' },
    { id: 27, name: 'Lincoln' },
    { id: 28, name: 'Alfa Romeo' },
    { id: 29, name: 'Mini' },
    { id: 30, name: 'Bentley' },
    { id: 31, name: 'Rolls-Royce' },
    { id: 32, name: 'Maserati' },
    { id: 33, name: 'Ferrari' },
    { id: 34, name: 'Lamborghini' },
    { id: 35, name: 'Aston Martin' },
    { id: 36, name: 'Bugatti' },
    { id: 37, name: 'McLaren' },
    { id: 38, name: 'Pagani' },
    { id: 39, name: 'Koenigsegg' },
    { id: 40, name: 'Lotus' },
    { id: 41, name: 'Smart' },
    { id: 42, name: 'Scion' },
    { id: 43, name: 'Genesis' },
    { id: 44, name: 'Polestar' },
    { id: 45, name: 'Rivian' },
    { id: 46, name: 'Lucid Motors' },
    { id: 47, name: 'Faraday Future' },
    { id: 48, name: 'Canoo' },
    { id: 49, name: 'Lordstown Motors' },
    { id: 50, name: 'Fisker Inc.' },
    { id: 51, name: 'BYD' },
    { id: 52, name: 'Renault' },
    { id: 53, name: 'Peugeot' },
    { id: 54, name: 'Citroën' },
    { id: 55, name: 'Opel' },
    { id: 56, name: 'Seat' },
    { id: 57, name: 'Skoda' },
    { id: 58, name: 'Dacia' },
    { id: 59, name: 'Suzuki' },
    { id: 60, name: 'Tata Motors' },
  ])

  const carModels = ref([
    { id: 1, brandId: 1, name: 'Corolla' },
    { id: 2, brandId: 1, name: 'Camry' },
    { id: 3, brandId: 2, name: 'Civic' },
    { id: 4, brandId: 2, name: 'Accord' },
    { id: 5, brandId: 3, name: 'F-150' },
    { id: 6, brandId: 3, name: 'Mustang' },
    { id: 7, brandId: 4, name: 'Silverado' },
    { id: 8, brandId: 4, name: 'Malibu' },
    { id: 9, brandId: 5, name: 'Altima' },
    { id: 10, brandId: 52, name: 'Clio' },
    { id: 11, brandId: 52, name: 'Megane' },
    { id: 12, brandId: 53, name: '208' },
    { id: 13, brandId: 53, name: '308' },
    { id: 14, brandId: 54, name: 'C3' },
    { id: 15, brandId: 54, name: 'C4' },
    { id: 16, brandId: 55, name: 'Astra' },
    { id: 17, brandId: 55, name: 'Corsa' },
    { id: 18, brandId: 56, name: 'Ibiza' },
    { id: 19, brandId: 56, name: 'Leon' },
    { id: 20, brandId: 57, name: 'Fabia' },
    { id: 21, brandId: 57, name: 'Octavia' },
    { id: 22, brandId: 58, name: 'Duster' },
    { id: 23, brandId: 58, name: 'Sandero' },
    { id: 24, brandId: 59, name: 'Swift' },
    { id: 25, brandId: 59, name: 'Vitara' },
    { id: 26, brandId: 60, name: 'Nano' },
    { id: 27, brandId: 60, name: 'Indica' },
    { id: 28, brandId: 60, name: 'Safari' },
    { id: 29, brandId: 60, name: 'Hexa' },
    { id: 30, brandId: 60, name: 'Harrier' },
    { id: 31, brandId: 60, name: 'Nexon' },
    { id: 32, brandId: 60, name: 'Altroz' },
    { id: 33, brandId: 60, name: 'Punch' },
    { id: 34, brandId: 60, name: 'Tigor' },
    { id: 35, brandId: 60, name: 'Tiago' },
    { id: 36, brandId: 60, name: 'Zest' },
    { id: 37, brandId: 60, name: 'Bolt' },
    { id: 38, brandId: 7, name: 'Classe A' },
    { id: 39, brandId: 7, name: 'Classe C' },
    { id: 40, brandId: 8, name: 'Golf' },
    { id: 41, brandId: 8, name: 'Passat' },
    { id: 42, brandId: 9, name: 'Elantra' },
    { id: 43, brandId: 9, name: 'Sonata' },
    { id: 44, brandId: 10, name: 'Rio' },
    { id: 45, brandId: 10, name: 'Sportage' },
  ])

  const mockCars = ref([
    {
      id: 1,
      brandId: 52,
      modelId: 10,
      classId: 1,
      carType: 1,
      transmissionId: 1,
      fuelTypeId: 1,
      seatsId: 3,
      doorsId: 2,
      colorId: 1,
      carExtras: [1, 2, 3],
      carExtra: 1,
      priceDaily: 49,
    },
    {
      id: 2,
      brandId: 53,
      modelId: 12,
      classId: 2,
      carType: 2,
      transmissionId: 2,
      fuelTypeId: 2,
      seatsId: 4,
      doorsId: 4,
      colorId: 2,
      carExtras: [4, 5],
      carExtra: 2,
      priceDaily: 69,
    },
    {
      id: 3,
      brandId: 54,
      modelId: 14,
      classId: 3,
      carType: 3,
      transmissionId: 1,
      fuelTypeId: 3,
      seatsId: 5,
      doorsId: 4,
      colorId: 3,
      carExtras: [6, 7, 8],
      carExtra: 3,
      priceDaily: 89,
    },
    {
      id: 4,
      brandId: 55,
      modelId: 16,
      classId: 4,
      carType: 4,
      transmissionId: 2,
      fuelTypeId: 4,
      seatsId: 7,
      doorsId: 4,
      colorId: 4,
      carExtras: [9, 10],
      carExtra: 4,
      priceDaily: 109,
    },
    {
      id: 5,
      brandId: 56,
      modelId: 18,
      classId: 1,
      carType: 5,
      transmissionId: 1,
      fuelTypeId: 1,
      seatsId: 2,
      doorsId: 2,
      colorId: 5,
      carExtras: [11, 12],
      carExtra: 5,
      priceDaily: 39,
    },
    {
      id: 6,
      brandId: 57,
      modelId: 20,
      classId: 2,
      carType: 6,
      transmissionId: 2,
      fuelTypeId: 2,
      seatsId: 4,
      doorsId: 4,
      colorId: 6,
      carExtras: [13, 14],
      carExtra: 6,
      priceDaily: 59,
    },
    {
      id: 7,
      brandId: 58,
      modelId: 22,
      classId: 3,
      carType: 7,
      transmissionId: 1,
      fuelTypeId: 3,
      seatsId: 5,
      doorsId: 4,
      colorId: 7,
      carExtras: [15, 16],
      carExtra: 7,
      priceDaily: 79,
    },
    {
      id: 8,
      brandId: 59,
      modelId: 24,
      classId: 4,
      carType: 8,
      transmissionId: 2,
      fuelTypeId: 4,
      seatsId: 7,
      doorsId: 4,
      colorId: 8,
      carExtras: [17, 18],
      carExtra: 8,
      priceDaily: 99,
    },
    {
      id: 9,
      brandId: 60,
      modelId: 26,
      classId: 1,
      carType: 1,
      transmissionId: 1,
      fuelTypeId: 1,
      seatsId: 2,
      doorsId: 2,
      colorId: 9,
      carExtras: [19, 20],
      carExtra: 9,
      priceDaily: 29,
    },
    {
      id: 10,
      brandId: 60,
      modelId: 28,
      classId: 2,
      carType: 2,
      transmissionId: 2,
      fuelTypeId: 2,
      seatsId: 4,
      doorsId: 4,
      colorId: 10,
      carExtras: [1, 2, 3],
      carExtra: 10,
      priceDaily: 69,
    },
    {
      id: 11,
      brandId: 60,
      modelId: 30,
      classId: 3,
      carType: 3,
      transmissionId: 1,
      fuelTypeId: 3,
      seatsId: 5,
      doorsId: 4,
      colorId: 1,
      carExtras: [4, 5, 6],
      carExtra: 11,
      priceDaily: 89,
    },
    {
      id: 12,
      brandId: 60,
      modelId: 32,
      classId: 4,
      carType: 4,
      transmissionId: 2,
      fuelTypeId: 4,
      seatsId: 7,
      doorsId: 4,
      colorId: 2,
      carExtras: [7, 8, 9],
      carExtra: 12,
      priceDaily: 109,
    },
    {
      id: 13,
      brandId: 60,
      modelId: 34,
      classId: 1,
      carType: 5,
      transmissionId: 1,
      fuelTypeId: 1,
      seatsId: 2,
      doorsId: 2,
      colorId: 3,
      carExtras: [10, 11, 12],
      carExtra: 13,
      priceDaily: 39,
    },
    {
      id: 14,
      brandId: 60,
      modelId: 36,
      classId: 2,
      carType: 6,
      transmissionId: 2,
      fuelTypeId: 2,
      seatsId: 4,
      doorsId: 4,
      colorId: 4,
      carExtras: [13, 14, 15],
      carExtra: 14,
      priceDaily: 59,
    },
    {
      id: 15,
      brandId: 60,
      modelId: 38,
      classId: 3,
      carType: 7,
      transmissionId: 1,
      fuelTypeId: 3,
      seatsId: 5,
      doorsId: 4,
      colorId: 5,
      carExtras: [16, 17, 18],
      carExtra: 15,
      priceDaily: 79,
    },
    {
      id: 16,
      brandId: 60,
      modelId: 40,
      classId: 4,
      carType: 8,
      transmissionId: 2,
      fuelTypeId: 4,
      seatsId: 7,
      doorsId: 4,
      colorId: 6,
      carExtras: [19, 20, 1],
      carExtra: 16,
      priceDaily: 99,
    },
    {
      id: 17,
      brandId: 60,
      modelId: 42,
      classId: 1,
      carType: 1,
      transmissionId: 1,
      fuelTypeId: 1,
      seatsId: 2,
      doorsId: 2,
      colorId: 7,
      carExtras: [2, 3, 4],
      carExtra: 17,
      priceDaily: 29,
    },
    {
      id: 18,
      brandId: 60,
      modelId: 44,
      classId: 2,
      carType: 2,
      transmissionId: 2,
      fuelTypeId: 2,
      seatsId: 4,
      doorsId: 4,
      colorId: 8,
      carExtras: [5, 6, 7],
      carExtra: 18,
      priceDaily: 69,
    },
  ])

  return {
    carClasses,
    carTypes,
    carBrands,
    carTransmission,
    carFuelType,
    carSeats,
    carDoors,
    carColors,
    carExtras,
    carModels,
    mockCars,
  }
})
